# Generated by Django 3.0.5 on 2020-10-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201017_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='score',
        ),
    ]
