# Generated by Django 3.0.5 on 2020-10-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201012_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
