# Generated by Django 3.0.5 on 2020-10-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201021_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='category',
        ),
        migrations.AddField(
            model_name='titles',
            name='category',
            field=models.ManyToManyField(to='api.Categories'),
        ),
    ]
