# Generated by Django 3.0.5 on 2020-10-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201021_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='genres', related_query_name='query_genres', to='api.Genres'),
        ),
    ]
