# Generated by Django 3.0.5 on 2020-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201022_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, to='api.Genres', verbose_name='genre'),
        ),
    ]
